title: DSC180A-Methodology-5
tagline: Data Science Capstone
description: Fall 2023 at UC San Diego
author: Lisa Hwang
baseurl: '/' # the subpath of your site, e.g. /blog
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
# remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: bluecsd
search_enabled: true
heading_anchors: true
permalink: pretty
